# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: memory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'memory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmemory.proto\x12\tmemory.v1\x1a\x1cgoogle/protobuf/struct.proto\"o\n\x0fMemorizeRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x16\n\x0e\x61ssistant_text\x18\x03 \x01(\t\x12\x13\n\x0bmemory_type\x18\x04 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x05 \x01(\t\"\x8a\x01\n\x10MemorizeResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07item_id\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x0f\n\x07success\x18\x04 \x01(\x08\x12\r\n\x05saved\x18\x05 \x01(\x08\x12\x13\n\x0bskip_reason\x18\x06 \x01(\t\x12\r\n\x05\x65rror\x18\x07 \x01(\t\"v\n\rRecallRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\r\n\x05top_k\x18\x03 \x01(\x05\x12&\n\x05where\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x0e\n\x06method\x18\x05 \x01(\t\"M\n\nRecallItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x10\n\x08salience\x18\x04 \x01(\x02\"g\n\x0eRecallResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12$\n\x05items\x18\x02 \x03(\x0b\x32\x15.memory.v1.RecallItem\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"\x0f\n\rHealthRequest\"@\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t2\xd2\x01\n\rMemoryService\x12\x43\n\x08Memorize\x12\x1a.memory.v1.MemorizeRequest\x1a\x1b.memory.v1.MemorizeResponse\x12=\n\x06Recall\x12\x18.memory.v1.RecallRequest\x1a\x19.memory.v1.RecallResponse\x12=\n\x06Health\x12\x18.memory.v1.HealthRequest\x1a\x19.memory.v1.HealthResponseB.Z,go-backend/internal/memory/memorypb;memorypbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'memory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,go-backend/internal/memory/memorypb;memorypb'
  _globals['_MEMORIZEREQUEST']._serialized_start=57
  _globals['_MEMORIZEREQUEST']._serialized_end=168
  _globals['_MEMORIZERESPONSE']._serialized_start=171
  _globals['_MEMORIZERESPONSE']._serialized_end=309
  _globals['_RECALLREQUEST']._serialized_start=311
  _globals['_RECALLREQUEST']._serialized_end=429
  _globals['_RECALLITEM']._serialized_start=431
  _globals['_RECALLITEM']._serialized_end=508
  _globals['_RECALLRESPONSE']._serialized_start=510
  _globals['_RECALLRESPONSE']._serialized_end=613
  _globals['_HEALTHREQUEST']._serialized_start=615
  _globals['_HEALTHREQUEST']._serialized_end=630
  _globals['_HEALTHRESPONSE']._serialized_start=632
  _globals['_HEALTHRESPONSE']._serialized_end=696
  _globals['_MEMORYSERVICE']._serialized_start=699
  _globals['_MEMORYSERVICE']._serialized_end=909
# @@protoc_insertion_point(module_scope)
