# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import memory_pb2 as memory__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in memory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemoryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Memorize = channel.unary_unary(
                '/memory.v1.MemoryService/Memorize',
                request_serializer=memory__pb2.MemorizeRequest.SerializeToString,
                response_deserializer=memory__pb2.MemorizeResponse.FromString,
                _registered_method=True)
        self.Recall = channel.unary_unary(
                '/memory.v1.MemoryService/Recall',
                request_serializer=memory__pb2.RecallRequest.SerializeToString,
                response_deserializer=memory__pb2.RecallResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/memory.v1.MemoryService/Health',
                request_serializer=memory__pb2.HealthRequest.SerializeToString,
                response_deserializer=memory__pb2.HealthResponse.FromString,
                _registered_method=True)


class MemoryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Memorize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Memorize': grpc.unary_unary_rpc_method_handler(
                    servicer.Memorize,
                    request_deserializer=memory__pb2.MemorizeRequest.FromString,
                    response_serializer=memory__pb2.MemorizeResponse.SerializeToString,
            ),
            'Recall': grpc.unary_unary_rpc_method_handler(
                    servicer.Recall,
                    request_deserializer=memory__pb2.RecallRequest.FromString,
                    response_serializer=memory__pb2.RecallResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=memory__pb2.HealthRequest.FromString,
                    response_serializer=memory__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memory.v1.MemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memory.v1.MemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Memorize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.MemoryService/Memorize',
            memory__pb2.MemorizeRequest.SerializeToString,
            memory__pb2.MemorizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Recall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.MemoryService/Recall',
            memory__pb2.RecallRequest.SerializeToString,
            memory__pb2.RecallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.MemoryService/Health',
            memory__pb2.HealthRequest.SerializeToString,
            memory__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
